run:
  timeout: 10m

linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - errcheck
    - exhaustive
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  funlen:
    lines: 70
    statements: 40
  lll:
    line-length: 200
  govet:
    enable-all: true
    disable:
      - fieldalignment
  dupl:
    threshold: 200
  exhaustive:
    default-signifies-exhaustive: true
  gocognit:
    min-complexity: 10

issues:
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - funlen
    - path: _test\.go
      text: Potential hardcoded credentials
  exclude:
    - "underscores in Go names"
