version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: commerce-database
    environment:
      POSTGRES_USER: commerce
      POSTGRES_PASSWORD: commerce
      POSTGRES_DB: commerce
    ports:
      - "5432:5432"
    volumes:
      - commerce-storage:/var/lib/postgresql/data
    networks:
      - commerce-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      - commerce-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

networks:
  commerce-network:

volumes:
  commerce-storage:
  grafana-storage:
