// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbgen

import (
	"context"
)

type Querier interface {
	AddProduct(ctx context.Context, arg AddProductParams) (int64, error)
	AddProductToStock(ctx context.Context, arg AddProductToStockParams) error
	CreateOrder(ctx context.Context, arg CreateOrderParams) (int64, error)
	CreateShop(ctx context.Context, arg CreateShopParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) error
	DecreaseStock(ctx context.Context, arg DecreaseStockParams) (int64, error)
	GetProductByID(ctx context.Context, id int64) (GetProductByIDRow, error)
	GetProducts(ctx context.Context) ([]GetProductsRow, error)
	GetProductsByShopID(ctx context.Context, shopID int64) ([]GetProductsByShopIDRow, error)
	GetUserByEmailOrPhone(ctx context.Context, arg GetUserByEmailOrPhoneParams) (Users, error)
	GetWarehousesByShopID(ctx context.Context, shopID int64) ([]GetWarehousesByShopIDRow, error)
	IncreaseStock(ctx context.Context, arg IncreaseStockParams) (int64, error)
	ReserveStock(ctx context.Context, arg ReserveStockParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (UpdateOrderStatusRow, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error
	UpdateWarehouseStatus(ctx context.Context, arg UpdateWarehouseStatusParams) error
}

var _ Querier = (*Queries)(nil)
