// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: shops.sql

package dbgen

import (
	"context"
)

const createShop = `-- name: CreateShop :exec
INSERT INTO shops(name, address) VALUES ($1, $2)
`

type CreateShopParams struct {
	Name    string `db:"name"`
	Address string `db:"address"`
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) error {
	_, err := q.db.Exec(ctx, createShop, arg.Name, arg.Address)
	return err
}
